export const HOMEPAGE_OSS_ASSET_MAP: Record<string, string> = {
  "/images/gpt-image-2.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/gpt-image-2.png",
  "/images/video-community/video-demo-1.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-1.mp4",
  "/images/video-community/video-demo-1.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-1.png",
  "/images/video-community/video-demo-10.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-10.mp4",
  "/images/video-community/video-demo-10.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-10.png",
  "/images/video-community/video-demo-11.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-11.mp4",
  "/images/video-community/video-demo-11.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-11-crop-20260605.png",
  "/images/video-community/video-demo-12.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-12.mp4",
  "/images/video-community/video-demo-12.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-12-square-20260605.png",
  "/images/video-community/video-demo-2.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-2.mp4",
  "/images/video-community/video-demo-2.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-2.png",
  "/images/video-community/video-demo-3.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-3.mp4",
  "/images/video-community/video-demo-3.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-3.png",
  "/images/video-community/video-demo-4.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-4.mp4",
  "/images/video-community/video-demo-4.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-4.png",
  "/images/video-community/video-demo-5.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-5.mp4",
  "/images/video-community/video-demo-5.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-5-crop-20260605.png",
  "/images/video-community/video-demo-6.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-6.mp4",
  "/images/video-community/video-demo-6.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-6.png",
  "/images/video-community/video-demo-7.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-7.mp4",
  "/images/video-community/video-demo-7.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-7.png",
  "/images/video-community/video-demo-8.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-8.mp4",
  "/images/video-community/video-demo-8.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-8-crop-20260605.png",
  "/images/video-community/video-demo-9.mp4": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-9.mp4",
  "/images/video-community/video-demo-9.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/images/video-community/video-demo-9-square-20260605.png",
  "/models/Flux-2.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Flux-2.jpg",
  "/models/Flux-Dev.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Flux-Dev.jpg",
  "/models/Flux-Kontext.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Flux-Kontext.jpg",
  "/models/Flux-Krea.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Flux-Krea.jpg",
  "/models/grok-imagine-1.0.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/grok-imagine-1.0.jpg",
  "/models/HiDream-full.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/HiDream-full.jpg",
  "/models/homepageModelCover/demo.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/demo.jpg",
  "/models/homepageModelCover/grok-imagine-1.0.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/grok-imagine-1.0.png",
  "/models/homepageModelCover/nano-banana-2.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/nano-banana-2.png",
  "/models/homepageModelCover/qwen-image-edit.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/qwen-image-edit.png",
  "/models/homepageModelCover/wai.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/wai.png",
  "/models/homepageModelCover/wai17.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/wai17.png",
  "/models/homepageModelCover/Z-Image-turbo.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/Z-Image-turbo.png",
  "/models/homepageModelCover/Z-Image.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/homepageModelCover/Z-Image.png",
  "/models/nano-banana-2.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/nano-banana-2.jpg",
  "/models/Qwen-Image.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Qwen-Image.jpg",
  "/models/StableDiffusion-3.5.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/StableDiffusion-3.5.jpg",
  "/models/Wai-SDXL-V150.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Wai-SDXL-V150.jpg",
  "/models/Wai-SDXL-V170.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Wai-SDXL-V170.jpg",
  "/models/Z-Image-Turbo.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Z-Image-Turbo.jpg",
  "/models/Z-Image.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/models/Z-Image.jpg",
  "/workflows/homepageWorkflowCover/demo.jpg": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/workflows/homepageWorkflowCover/demo.jpg",
  "/workflows/homepageWorkflowCover/fix.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/workflows/homepageWorkflowCover/fix.png",
  "/workflows/homepageWorkflowCover/scale.png": "https://dreamifly.oss-cn-shanghai.aliyuncs.com/homepage-assets/workflows/homepageWorkflowCover/scale.png",
};

export function getHomepageAsset(localPath: string): string {
  return HOMEPAGE_OSS_ASSET_MAP[localPath] || localPath;
}

export function getHomepageAssetFallback(assetPath: string, fallbackPath?: string): string {
  return fallbackPath || (assetPath.startsWith('/') ? assetPath : '');
}
